[project]
name = "pet-mail-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosmtplib>=4.0.2",
    "faststream[cli,kafka]>=0.5.48",
    "pydantic-settings>=2.10.1",
    "pydantic[email]>=2.11.9",
]
